### PR TITLE
Language support change

### PR DESCRIPTION
**Pull request by Julienraptor01**
sodium link is now crowdin

escape chars in hyperlinks are actually not needed
you can test the cull less leaves link in actual wiki by example

### CODE REVIEW

**Comment by Madis0** [comment]
Sodium link was intentionally GitHub so that people would learn what it is and how it works before they contribute to it (especially because it's unofficial).

Escaped links I'm not sure about, might be automatically done by GitBook.

**Comment by Julienraptor01** [comment]
> Sodium link was intentionally GitHub so that people would learn what it is and how it works before they contribute to it (especially because it's unofficial).
> 
> Escaped links I'm not sure about, might be automatically done by GitBook.

ok for sodium link i tought it was an error

for escaped links yeah it seems the editor does that automatically
however it work fine without and in addition it makes links work fine when you open them from a regular editor

**Comment by Madis0** [comment]
If it does it automatically, why would I merge the PR though? As it will be reverted by it anyway.

**Comment by Julienraptor01** [comment]
> If it does it automatically, why would I merge the PR though? As it will be reverted by it anyway.

it only put the esc chars when you create or modify the exact text in gitbook
and if i look at history you seemed to be the only one to use gitbook's editor

**Comment by Madis0** [comment]
Ok, let's try it then. But if it breaks, be prepared to do a reverse PR 😄

**Pull request merged**
