### PR TITLE
Russian wiki

### PR DESCRIPTION
**Pull request by RozeFound**
Of course it's draft, hell a lot of work must be done. Not for single commit.

### CODE REVIEW

**Review by Madis0 — CHANGES_REQUESTED** [review]
Please keep the filenames ascii just in case, e.g. besplatnyj-plashh.md

**Comment by RozeFound** [comment]
Isn't it just a recommendation? If it's not, so better just leave English names

**Comment by Madis0** [comment]
Well this would be a really ugly URL 😄
https://github.com/RozeFound/wiki/edit/patch-1/ru-ru/%D0%BE%D1%82%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BC%D0%BE%D0%B4%D0%BE%D0%B2.md
Yes, you can keep English names as well.

**Comment by RozeFound** [comment]
Well, you don't have to provide encoded url 
https://github.com/RozeFound/wiki/blob/patch-1/ru-ru/отключение-модов.md works too

**Comment by Madis0** [comment]
That depends on the URL parser, could break in some places.

**Comment by RozeFound** [comment]
Who is gonna parse wiki...? But, yeah, I got your point. Will keep names in English

**Comment by RozeFound** [comment]
I lost any interest in completing this. Sorry.

**Pull request closed without merging**
